services:
  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "5001:8080"
    volumes:
      - ./src/test/resources/wiremock:/home/wiremock
    command:
      - -global-response-templating
  minio:
    image: "minio/minio:RELEASE.2024-01-29T03-56-32Z"
    ports:
      #      MINIO CONSOLE API AND GUI
      - "9000:9000"
      - "9001:9001"
    volumes:
      - './minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKET=user_preferences
    command: server /data --console-address ":9001"