spring:
  cloud:
    aws:
      credentials:
        access-key: minioadmin
        secret-key: minioadmin
      s3:
        region: us-east-1
        endpoint: http://localhost:9000
        path-style-access-enabled: true
